defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: hackid_rails_development

test:
  <<: *defaults
  database: hackid_rails_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database:  <%= ENV['MONGOMAPPER_DATABASE'] %>
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
